pipeline:
  npm_auth:
    image: robertstettner/drone-npm-auth
    registry: https://drone-npm.neocodenetworks.org
    secrets: [ npm_username, npm_password, npm_email ]

  build:
    image: node:carbon-alpine
    commands:
      - npm install
      - npm run build

  test:
    image: node:carbon-alpine
    commands:
      - npm run test || true # Don't fail this step
      - npm run test:upload
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    environment:
      - NODE_ENV=test
      - redis__host=redis

  publish_npm:
    image: plugins/npm
    registry: https://drone-npm.neocodenetworks.org
    folder: client_types
    when:
      event: deployment
      environment: production-npm

  publish_docker_master:
    image: plugins/docker
    registry: drone-registry.neocodenetworks.org
    repo: drone-registry.neocodenetworks.org/mue/server
    secrets: [ docker_username, docker_password ]
    tag: [ latest, master ]
    when:
      branch: master
      event: push

  publish_docker_branch:
    image: plugins/docker
    registry: drone-registry.neocodenetworks.org
    repo: drone-registry.neocodenetworks.org/mue/server
    secrets: [ docker_username, docker_password ]
    tag: ${DRONE_BRANCH}
    when:
      branch:
        exclude: master
      event: push

  publish_docker_tag:
    image: plugins/docker
    registry: drone-registry.neocodenetworks.org
    repo: drone-registry.neocodenetworks.org/mue/server
    secrets: [ docker_username, docker_password ]
    tag: ${DRONE_TAG}
    when:
      event: tag

  publish_docker_to_prod:
    image: plugins/docker
    registry: drone-registry.neocodenetworks.org
    repo: drone-registry.neocodenetworks.org/mue/server
    secrets: [ docker_username, docker_password ]
    tag: prod
    when:
      event: deployment
      environment: production

  notify_neopush:
    image: drone-registry.neocodenetworks.org/neopush/drone
    pull: true
    secrets: [ neopush_api_key ]

services:
  redis:
    image: redis
