pipeline:
  npm_auth:
    image: robertstettner/drone-npm-auth
    registry: https://npm.cloud.neocodenetworks.org
    secrets: [ npm_username, npm_password, npm_email ]

  build:
    image: node:carbon-alpine
    commands:
      - npm install
      - npm run build

  test:
    image: node:carbon-alpine
    commands:
      - npm run test
    environment:
      - NODE_ENV=test
      - redis__host=redis
    when:
      event:
        - push
        - pull_request

  publish_test_report:
    image: plugins/s3-sync
    bucket: drone-test-results
    source: ./mochawesome-report/
    target: mue-server/${DRONE_BRANCH}/report/
    delete: true
    acl:
      "*": public-read
    path_style: true
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key ]
    errignore: true
    when:
      event: push

  publish_test_cov:
    image: plugins/s3-sync
    bucket: drone-test-results
    source: ./coverage/
    target: mue-server/${DRONE_BRANCH}/coverage/
    delete: true
    acl:
      "*": public-read
    path_style: true
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key ]
    errignore: true
    when:
      event: push

  publish_npm:
    image: plugins/npm
    registry: https://npm.cloud.neocodenetworks.org
    folder: client_types
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      event: deployment
      environment: production-npm

  publish_docker_master:
    image: plugins/docker
    registry: docker.cloud.neocodenetworks.org
    repo: docker.cloud.neocodenetworks.org/mue/server
    secrets: [ docker_username, docker_password ]
    tag: [ latest, master ]
    when:
      branch: master
      event: push

  publish_docker_branch:
    image: plugins/docker
    registry: docker.cloud.neocodenetworks.org
    repo: docker.cloud.neocodenetworks.org/mue/server
    secrets: [ docker_username, docker_password ]
    tag: ${DRONE_BRANCH}
    when:
      branch:
        exclude: master
      event: push

  publish_docker_tag:
    image: plugins/docker
    registry: docker.cloud.neocodenetworks.org
    repo: docker.cloud.neocodenetworks.org/mue/server
    secrets: [ docker_username, docker_password ]
    tag: ${DRONE_TAG}
    when:
      event: tag

  publish_docker_to_prod:
    image: plugins/docker
    registry: docker.cloud.neocodenetworks.org
    repo: docker.cloud.neocodenetworks.org/mue/server
    secrets: [ docker_username, docker_password ]
    tag: prod
    when:
      event: deployment
      environment: production

  notify_neopush:
    image: docker.cloud.neocodenetworks.org/neopush/drone
    pull: true
    secrets: [ neopush_api_key ]
    errignore: true

services:
  redis:
    image: redis
