version: '3'
services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
  app:
    image: node:carbon-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS__HOST=redis
    restart: on-failure

volumes:
  redis-data:
